# Generated by Django 4.1.3 on 2022-11-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat_linebot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='random_exam',
            name='num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='random_exam',
            name='question',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
