# Generated by Django 4.1.3 on 2022-11-28 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat_linebot', '0004_乖乖吃飯'),
    ]

    operations = [
        migrations.AddField(
            model_name='乖乖吃飯',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
