# Generated by Django 4.1.3 on 2022-11-30 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat_linebot', '0006_pidan_心靈雞湯_rename_grans_乖乖吃飯_grams'),
    ]

    operations = [
        migrations.CreateModel(
            name='toy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=0)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('price', models.CharField(blank=True, default='', max_length=255)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='心靈雞湯',
            name='kcal',
        ),
        migrations.AddField(
            model_name='user_info',
            name='ansdt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
