# Generated by Django 4.1.3 on 2022-11-30 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat_linebot', '0007_toy_remove_心靈雞湯_kcal_user_info_ansdt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='ansdt',
            field=models.DateTimeField(default='2018-06-14 21:17:08.132263'),
        ),
    ]
