# Generated by Django 4.1.3 on 2022-11-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat_linebot', '0008_alter_user_info_ansdt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='mdt',
            field=models.DateTimeField(),
        ),
    ]
