# Generated by Django 4.1.3 on 2022-12-01 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat_linebot', '0009_alter_user_info_mdt'),
    ]

    operations = [
        migrations.AddField(
            model_name='pidan',
            name='times',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='toy',
            name='times',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='乖乖吃飯',
            name='times',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='心靈雞湯',
            name='times',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='ansdt',
            field=models.DateTimeField(default='2018-06-14 21:17:08.132263+00:00'),
        ),
    ]
