# Generated by Django 4.1.3 on 2022-12-02 08:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat_linebot', '0010_pidan_times_toy_times_乖乖吃飯_times_心靈雞湯_times_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='ansdt',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 14, 13, 17, 8, 132263, tzinfo=datetime.timezone.utc)),
        ),
    ]
